#!/usr/bin/env bash

if [ $# -eq 0 ]; then
	echo "Usage:"
	echo "mvregex-transliterate-windows [-p] FILE..."
	exit 1
fi

if [ "$1" = '-p' ]; then
	shift
	echo "Remove trailing spaces on all files recursively"
	mvregex -p -r '^(.*) +$' '\1' "$@"
	echo "Remove trailing spaces (cygwin encoded byte sequence EF80A8) on all files recursively"
	mvregex -p -r '^(.*)\xEF\x80\xA8$' '\1' "$@"
	echo "Remove trailing . on all files recursively"
	mvregex -p -r '^(.*)\.+$' '\1' "$@"
	echo "Remove trailing . (cygwin encoded byte sequence EF80A9) on all files recursively"
	mvregex -p -r '^(.*)\xEF\x80\xA9$' '\1' "$@"
else
	echo "Remove trailing spaces on all files recursively"
	mvregex -v -r '^(.*) +$' '\1' "$@"
	echo "Remove trailing spaces (cygwin encoded byte sequence EF80A8) on all files recursively"
	mvregex -v -r '^(.*)\xEF\x80\xA8$' '\1' "$@"
	echo "Remove trailing . on all files recursively"
	mvregex -v -r '^(.*)\.+$' '\1' "$@"
	echo "Remove trailing . (cygwin encoded byte sequence EF80A9) on all files recursively"
	mvregex -v -r '^(.*)\xEF\x80\xA9$' '\1' "$@"
fi
