#!/bin/bash

#----------------------------------------------------------------------------
# mvregex
# Copyright (C) 2007 Nathan Shearer
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to:
#   The Free Software Foundation Inc.
#   51 Franklin Street
#   Fifth Floor
#   Boston, MA
#   02110-1301
#   USA

COPYRIGHT="Copyright (C) 2009 Nathan Shearer"
VERSION="1.0.0.0"

if [ $# -eq 0 -o "$1" = "-h" -o "$1" = "--help" ]; then
	echo "mvregex moves any files that match the given regular expression."
	echo "Usage:"
	echo "  mvregex <source_regex> <destination_regex> <files>"
	echo "    Moves any <files> that match <source_regex> to <destination_regex>."
	echo "  mvregex -d <source_regex> <destination_regex> <files>"
	echo "    Performs a dry run and prints out what files will be moved. No"
	echo "    files are actually moved."
	exit 0;
fi

case "$1" in
	"-d")
		shift
		SOURCE_REGEX="$1"; shift
		DESTINATION_REGEX="$1"; shift
		for FILE in "$@"; do
			DESTINATION=`echo -n "$FILE" | sed -r "s/$SOURCE_REGEX/$DESTINATION_REGEX/"`
			echo "$FILE -> $DESTINATION"
		done
		;;
	*)
		SOURCE_REGEX="$1"; shift
		DESTINATION_REGEX="$1"; shift
		for FILE in "$@"; do
			DESTINATION=`echo -n "$FILE" | sed -r "s/$SOURCE_REGEX/$DESTINATION_REGEX/"`
			if [ "$FILE" != "$DESTINATION" ]; then
				mv -i "$FILE" "$DESTINATION"
			fi
		done
		;;
esac
