#!/bin/bash

#----------------------------------------------------------------------------
# Wintree
# Copyright (C) 2007 Nathan Shearer
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to:
#   The Free Software Foundation Inc.
#   51 Franklin Street
#   Fifth Floor
#   Boston, MA
#   02110-1301
#   USA

COPYRIGHT="Copyright (C) 2007 Nathan Shearer"
VERSION="1.0.0.0"

function wintree_convert
{
	mkdir -p "$2"
	for FILE in "$1"/*; do
		if [ "$FILE" = "$1/*" ]; then
			continue
		fi
		local LINNAME=`basename "$FILE"`
		# convert asterisk to _
		local WINNAME="$LINNAME"
		# convert backslash to _
		WINNAME=`printf "$WINNAME" | sed 's/\/_/g'`
		# convert colon to ratio
		#WINNAME=`printf "$WINNAME" | sed 's/:/∶/g'`
		
		#local WINNAME=`basename "$FILE" | tr "\\\\:*?\"<>|" _`
		if [ -d "$FILE" ]; then
			wintree_convert "$FILE" "$2/$WINNAME"
			continue
		fi
		ln -s "$1/$LINNAME" $2/${WINNAME}
		if [ "$LINNAME" != "$WINNAME" ]; then
			echo "\"$1/$LINNAME\" -> \"$2/$WINNAME\""
		fi
	done
}

function wintree_help
{
	echo "Wintree converts a tree of files and folders into a tree of folders and symbolic"
	echo "links with windows friendly filenames."
	echo ""
	echo "Usage:"
	echo "  wintree <linux_tree> <windows_tree>"
	echo "Options:"
	echo "  -h"
	echo "    Display this help message and exit."
	echo "  -v"
	echo "    Print the version and exit."
	echo "Examples:"
	echo "  wintree storage windows_storage"
}

function wintree_version
{
	echo "Wintree $VERSION $COPYRIGHT"
}

# defaults

# load configuration

# parse command line arguments
if [ $# -eq 0 ]; then
	wintree_help
	exit
fi
while getopts "hv" OPTION; do
	case "$OPTION" in
		"h") wintree_help; exit;;
		"v") wintree_version; exit;;
		*) wintree_help; exit;;
	esac
done
shift $(($OPTIND - 1))
LINTREE=`readlink -f "$1"`
mkdir -p "$2"
WINTREE=`readlink -f "$2"`
shift 2

# prepare environment

# begin execution

cp -rs "$LINTREE" "$WINTREE"
find "$WINTREE" 