#!/bin/bash

NAME="wintree"
CODENAME="wintree"
COPYRIGHT="Copyright (C) 2007 Nathan Shearer"
LICENSE="GNU General Public License 2.0"
VERSION="1.1.0.0"

function wintree_convert
{
	mkdir -p "$2"
	for FILE in "$1"/*; do
		if [ "$FILE" = "$1/*" ]; then
			continue
		fi
		local LINNAME=$(basename "$FILE")
		local WINNAME=$(basename "$FILE")
		## convert UTF-8 to ascii
		#WINNAME=$(echo -n "$WINNAME" | iconv -t ascii//TRANSLIT)
		# convert backslashes to underscore
		WINNAME=$(echo -n "$WINNAME" | tr '\\\\' _)
		# convert colon to ratio
		WINNAME=$(echo -n "$WINNAME" | sed 's/:/∶/g')
		# convert asterisk to heavy asterisk
		WINNAME=$(echo -n "$WINNAME" | sed 's/\*/✱/g')
		# convert to interrobang
		WINNAME=$(echo -n "$WINNAME" | sed -r "s/\!\?/‽/g")
		WINNAME=$(echo -n "$WINNAME" | sed -r "s/\?\!/‽/g")
		# convert question mark to underscore
		WINNAME=$(echo -n "$WINNAME" | sed 's/\?/_/g')
		# convert double quote to two single quotes
		WINNAME=$(echo -n "$WINNAME" | sed "s/\"/\'\'/g")
		# convert pipe to underscore
		WINNAME=$(echo -n "$WINNAME" | sed 's/|/_/g')
		# convert the rest to underscore
		WINNAME=$(echo -n "$WINNAME" | tr "<>|" _)
		if [ -d "$FILE" ]; then
			wintree_convert "$FILE" "$2/$WINNAME"
			continue
		fi
		if ! $PRETEND; then
			if [ "$LINK_TYPE" = "symbolic" ]; then
				cp -s "$1/$LINNAME" "$2/${WINNAME}"
			elif [ "$LINK_TYPE" = "hard" ]; then
				cp -l "$1/$LINNAME" "$2/${WINNAME}"
			fi
		fi
		if [ "$LINNAME" != "$WINNAME" ]; then
			echo "'$1/$LINNAME' -> '$2/$WINNAME'"
		fi
	done
}

# \brief Displays the help and exits the program
function wintree_help
{
	#     01234567890123456789012345678901234567890123456789012345678901234567890123456789
	echo "Description:"
	echo "  Recursively copies a directory into windows friendly filenames."
	echo
	echo "Usage:"
	echo "  $CODENAME [options] <linux_dir> <windows_dir>"
	echo
	echo "Options:"
	echo "  -h, --help"
	echo "    Display this help message and exit."
	echo "  -l, --link"
	echo "    Hard link files instead of creating symbolic links."
	echo "  -p, --pretend"
	echo "    Do not make any changes. Output files that are renamed in the destination."
	echo "  -s, --symbolic-link"
	echo "    Make symbolic links instead of hard links. Enabled by default."
	echo
	echo "Examples:"
	echo "  wintree -p /mnt/storage /mnt/storage.wintree"
	echo "  wintree -p -l /mnt/storage /mnt/storage.wintree"
	echo
	echo "Version:"
	echo "  $NAME $VERSION"
	echo "  $COPYRIGHT"
	echo "  Licensed under $LICENSE"
	exit
}

#------------------------------------------------------------------------------
# default configuration

LINK_TYPE=symbolic
PRETEND=false

#------------------------------------------------------------------------------
# command line arguments

while [ $# -ne 2 ]; do
	case "$1" in
		"-h"|"--help")
			wintree_help
			exit
			;;
		"-l"|"--link")
			LINK_TYPE=hard
			shift
			;;
		"-p"|"--pretend")
			PRETEND=true
			shift
			;;
		"-s"|"--symbolic-link")
			LINK_TYPE=symbolic
			shift
			;;
		*)
			wintree_help
			exit
			;;
	esac
done
LINDIR=$(readlink -f "$1")
mkdir -p "$2"
WINDIR=$(readlink -f "$2")
shift 2

#------------------------------------------------------------------------------
# begin execution

wintree_convert "$LINDIR" "$WINDIR"
